repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        language: system
        entry: bash -c 'poetry run flake8'
        types: [python]
    -   id: black
        name: black
        language: system
        entry: bash -c 'poetry run black .'
        types: [python]
    -   id: mypy
        name: mypy
        language: system
        entry: bash -c 'poetry run mypy .'
        types: [python]
    -   id: isort
        name: isort
        language: system
        entry: bash -c 'poetry run isort --profile black .'
        types: [python]
    -   id: pylint
        name: pylint
        language: system
        entry: bash -c 'poetry run pylint --disbale R,C'
        types: [python]
